// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBleanRS5JcU8q-MaCy7KRAHTDtWi2Kzo4',
    appId: '1:367310603826:web:8ac36ef73a388892ef9e2b',
    messagingSenderId: '367310603826',
    projectId: 'arnoldgym-de70a',
    authDomain: 'arnoldgym-de70a.firebaseapp.com',
    storageBucket: 'arnoldgym-de70a.firebasestorage.app',
    measurementId: 'G-H8D8H6BJWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ZQrlhz7Ut0hFbt6O750fmXHQ4h2ACa8',
    appId: '1:367310603826:android:698b461dbe12892aef9e2b',
    messagingSenderId: '367310603826',
    projectId: 'arnoldgym-de70a',
    storageBucket: 'arnoldgym-de70a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwmLLJgUb5jlyfubpU2DxkpxNyPGBC9TM',
    appId: '1:367310603826:ios:9a97c55a0753851cef9e2b',
    messagingSenderId: '367310603826',
    projectId: 'arnoldgym-de70a',
    storageBucket: 'arnoldgym-de70a.firebasestorage.app',
    iosBundleId: 'com.example.arnoldgym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwmLLJgUb5jlyfubpU2DxkpxNyPGBC9TM',
    appId: '1:367310603826:ios:9a97c55a0753851cef9e2b',
    messagingSenderId: '367310603826',
    projectId: 'arnoldgym-de70a',
    storageBucket: 'arnoldgym-de70a.firebasestorage.app',
    iosBundleId: 'com.example.arnoldgym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBleanRS5JcU8q-MaCy7KRAHTDtWi2Kzo4',
    appId: '1:367310603826:web:907cbf367c94ae78ef9e2b',
    messagingSenderId: '367310603826',
    projectId: 'arnoldgym-de70a',
    authDomain: 'arnoldgym-de70a.firebaseapp.com',
    storageBucket: 'arnoldgym-de70a.firebasestorage.app',
    measurementId: 'G-798R3B5C6S',
  );
}
